name: upload-test-labels
author: Data
description: Parse test labels in a project and upload them to S3 to be ingested to the data warehouse

inputs:
  repository_name:
    description: The name of the repository in which to parse test labels
    required: true
  projects:
    description: The projects containing tests to parse. Full path to the dll, comma separated.
    required: true 

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Restore NuGet Packages
      run: nuget restore ${{ github.action_path }}/src/TestLabelReporting/TestLabelReporting.sln
      shell: pwsh

    # - name: Add msbuild to PATH
      # uses: microsoft/setup-msbuild@v2
          
    - name: Build Test Label Export Utility
      run: msbuild ${{ github.action_path }}/src/TestLabelReporting/TestLabelReporting.sln /p:OutputPath="\bin\artifacts"
      shell: pwsh

    - name: Run Test Label Export Utility
      run: |
       \bin\artifacts\TestLabelReporting.exe ${{ inputs.repository_name }} ${{ inputs.projects }}
      shell: pwsh